name: Build and Deploy React App to S3

on:
  push:
    branches:
      - main  # This runs the workflow on push events to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the Node.js version you need

    - name: Install dependencies
      #working-directory: ./react-app
      run: npm install

    - name: Build React app
      #working-directory: ./react-app
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust this to your S3 bucket's region
        aws-bucket-name:  ${{ secrets.AWS_S3_BUCKET_NAME }}
        aws-cloudfront-ID:  ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    - name: Upload to S3
      run: |
        aws s3 cp ./build/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/ --recursive

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
